[package]
name = "radio-streamer"
version = "0.1.0"
authors = ["Roman Lakhtadyr <roman.lakhtadyr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="4.0.0-beta.3"
serde_json = "1.0.60"
slog-json = "2.3.0"
slog = "2.7.0"
envy = "0.4.2"
features = "0.10.0"
actix-rt = "2.1.0"

[dependencies.serde]
version = "1.0.123"
features = ["derive"]

