[package]
name = "radio-streamer"
version = "0.1.8"
authors = ["Roman Lakhtadyr <roman.lakhtadyr@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 0

[dependencies]
actix-web = { version = "4.0.0-beta.4", features=["rustls"] }
actix-rt = "2.1.0"
awc = "3.0.0-beta.3"
serde_json = "1.0.60"
slog-json = "2.3.0"
slog = "2.7.0"
envy = "0.4.2"
futures = "0.3.13"
futures-lite = "1.11.3"
cargo-watch = "7.5.0"
serde = { version = "1.0.123", features = ["derive"] }
async-process = "1.0.2"
prometheus = { version = "0.12.0", features = ["process"] }
bytebuffer = "0.2.1"
uuid = { version = "0.8.2", features = ["v4"] }
