options:
  docker: true

pipelines:
  tags:
    v*:
     - step:
        deployment: production
        script:
          - export IMAGE_NAME=myownradio/backend-core:BITBUCKET_TAG
          - docker build -t $IMAGE_NAME .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
