options:
  docker: true

pipelines:
  branches:
    production:
      - step:
          script:
            - docker build -t $DOCKER_IMAGE .
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker push $DOCKER_IMAGE
      - step:
          deployment: production
          script:
            - ssh $DEPLOY_HOST -- docker service update --quiet --force --with-registry-auth --image=$DOCKER_IMAGE $DEPLOY_SERVICE
