version: "3.5"

services:
  traefik:
    depends_on:
      - backend-nginx
    networks:
      - myownradio-dev
    image: library/traefik:2.4
    ports:
      - "40180:80"
      - "40181:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
  db:
    build:
      context: ./images/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myownradio-dev
    ports:
      - "127.0.0.1:40001:3306"
  backend-nginx:
    depends_on:
      - backend-php-fpm
    image: myownradio/backend-nginx-base:1.0.2
    volumes:
      - ./services/backend:/code:ro
    networks:
      - myownradio-dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/`)
      - traefik.http.services.backend.loadbalancer.server.port=80
  backend-php-fpm:
    depends_on:
      - db
      - file-server
    image: myownradio/backend-php-base:3.0.3
    working_dir: /code
    volumes:
      - ./services/backend:/code:rw
    user: "${UID}:${GID}"
    networks:
      - myownradio-dev
    environment:
      COMPOSER_HOME: /code/.cache/composer-home
  migration:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./images/migration/Dockerfile
    networks:
      - myownradio-dev
    environment:
      MYSQL_DB: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
      MYSQL_HOST: "db"
  file-server:
    image: myownradio/file-server:1.0.2
    volumes:
      - ./services/backend/.cache/storage:/usr/share/nginx/html:ro
    ports:
      - "127.0.0.1:40004:80"
    networks:
      - myownradio-dev
  radio-streamer:
    depends_on:
      - radio-manager-backend
      - file-server
    build:
      context: ./services/radio-streamer
      dockerfile: Dockerfile-dev
    volumes:
      - ./services/radio-streamer:/code:rw
      - ./services/radio-streamer/.cargo-cache/git:/rust/.cargo/git
      - ./services/radio-streamer/.cargo-cache/registry:/rust/.cargo/registry
    user: "${UID}:${GID}"
    working_dir: /code
    command: cargo run
    networks:
      - myownradio-dev
    ports:
      - "127.0.0.1:40003:8080"
    environment:
      - HOME=/rust
      - LOG_LEVEL=Trace
      - LOG_FORMAT=Term
      - MOR_BACKEND_URL=http://radio-manager-backend:8080
      - STREAM_MUTATION_TOKEN=secret
      - BIND_ADDRESS=0.0.0.0:8080
  radio-manager-backend:
    build:
      context: services/radio-manager-backend
      dockerfile: Dockerfile-dev
    volumes:
      - ./services/radio-manager-backend:/code:rw
      - ./services/radio-manager-backend/.cargo-cache/git:/rust/.cargo/git
      - ./services/radio-manager-backend/.cargo-cache/registry:/rust/.cargo/registry
    user: "${UID}:${GID}"
    working_dir: /code
    command: cargo run
    networks:
      - myownradio-dev
    ports:
      - "127.0.0.1:40005:8080"
    environment:
      - HOME=/rust
      - LOG_LEVEL=Trace
      - LOG_FORMAT=Term
      - BIND_ADDRESS=0.0.0.0:8080
      - MYSQL_HOST=db
      - MYSQL_DATABASE=mor
      - MYSQL_USER=mor
      - MYSQL_PASSWORD=mor
      - FILE_SERVER_ENDPOINT=http://file-server:80/
    labels:
      - traefik.enable=true
      - traefik.http.routers.radioManager.rule=PathPrefix(`/radio-manager/api/`)
      - traefik.http.routers.radioManager.middlewares=stripprefixRadioManager,forwardauthRadioManager
      - traefik.http.routers.radioManagerPub.rule=PathPrefix(`/radio-manager/api/pub`)
      - traefik.http.routers.radioManagerPub.middlewares=stripprefixRadioManager
      - traefik.http.services.radioManager.loadbalancer.server.port=8080
      - traefik.http.middlewares.stripprefixRadioManager.stripprefix.prefixes=/radio-manager/api
      - traefik.http.middlewares.forwardauthRadioManager.forwardauth.address=http://backend-nginx:80/api/v2/me
      - traefik.http.middlewares.forwardauthRadioManager.forwardauth.authResponseHeaders=user-id
      - traefik.http.middlewares.forwardauthRadioManager.forwardauth.trustForwardHeader=false
volumes:
  mysql-data:
    driver: local

networks:
  myownradio-dev:
    name: myownradio-dev

