version: "3.5"

services:
  db:
    build:
      context: ./images/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myownradio-dev
    ports:
      - 127.0.0.1:40001:3306
  backend-nginx:
    depends_on:
      - backend-php-fpm
    image: myownradio/backend-nginx-base:1.0.2
    volumes:
      - ./services/backend:/code:ro
    networks:
      - myownradio-dev
    ports:
      - 127.0.0.1:40002:80
  backend-php-fpm:
    depends_on:
      - db
      - file-server
    image: myownradio/backend-php-base:3.0.2
    working_dir: /code
    volumes:
      - ./services/backend:/code:ro
      - user-data:/var/lib/mor/user-data
    user: www-data:www-data
    networks:
      - myownradio-dev
    environment:
      COMPOSER_HOME: /code/.cache/composer-home
  migration:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./images/migration/Dockerfile
    networks:
      - myownradio-dev
    environment:
      MYSQL_DB: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
      MYSQL_HOST: "db"
  file-server:
    image: myownradio/file-server:1.0.2
    volumes:
      - user-data:/usr/share/nginx/html:ro
    ports:
      - 127.0.0.1:40004:80
    networks:
      - myownradio-dev
  radio-streamer:
    depends_on:
      - backend-nginx
      - file-server
    build:
      context: ./services/radio-streamer
      dockerfile: Dockerfile-dev
    volumes:
      - ./services/radio-streamer:/code
      - ./services/radio-streamer/.cargo-cache/git:/rust/.cargo/git
      - ./services/radio-streamer/.cargo-cache/registry:/rust/.cargo/registry
    working_dir: /code
    command: cargo run
    networks:
      - myownradio-dev
    ports:
      - 127.0.0.1:40003:8080
    environment:
      - LOG_LEVEL=Debug
      - MOR_BACKEND_URL=http://backend-nginx
      - STREAM_MUTATION_TOKEN=secret
      - BIND_ADDRESS=0.0.0.0:8080

volumes:
  mysql-data:
    driver: local
  user-data:
    driver: local

networks:
  myownradio-dev:
    name: myownradio-dev

