version: "3.5"

services:
  db:
    build:
      context: ./images/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myownradio-dev
    ports:
      - 127.0.0.1:40001:3306
  backend-nginx:
    depends_on:
      - backend-php-fpm
    image: myownradio/backend-nginx-base:1.0.2
    volumes:
      - ./services/backend:/code:ro
    networks:
      - myownradio-dev
    ports:
      - 127.0.0.1:40002:80
  backend-php-fpm:
    depends_on:
      - db
    image: myownradio/backend-php-base:2.0.0
    working_dir: /code
    volumes:
      - ./services/backend:/code:ro
    user: "${UID}:${GID}"
    networks:
      - myownradio-dev
  migration:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./images/migration/Dockerfile
    networks:
      - myownradio-dev
    environment:
      MYSQL_DB: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
      MYSQL_HOST: "db"

volumes:
  mysql-data:
    driver: local

networks:
  myownradio-dev:
    name: myownradio-dev

