version: '3.5'
services:
  db:
    image: 'mysql:5.6'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      update_config:
        order: stop-first
        failure_action: rollback
      resources:
        limits:
          memory: 1024M
  radio-streamer:
    image: myownradio/radio-streamer:latest
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - MOR_BACKEND_URL=http://backend-nginx:8080
      - STREAM_MUTATION_TOKEN=2a74df546ce14acbb01fd71f1d00dfe7
      - LOG_LEVEL=Debug
    networks:
      - default
      - global
    depends_on:
      - backend-nginx
    deploy:
      labels:
        - prometheus-job=radio-streamer
        - prometheus-port=8080
        - traefik.enable=true
        - traefik.http.routers.myownradio_rstreamer.entryPoints=web,websecure
        - traefik.http.routers.myownradio_rstreamer.rule=Host(`myownradio.biz`) && PathPrefix(`/r/`)
        - traefik.http.routers.myownradio_rstreamer.tls=true
        - traefik.http.routers.myownradio_rstreamer.tls.certresolver=resolver
        - traefik.http.routers.myownradio_rstreamer.middlewares=stripprefix_myownradio_rstreamer
        - traefik.http.services.myownradio_rstreamer.loadbalancer.server.port=8080
        - traefik.http.middlewares.stripprefix_myownradio_rstreamer.stripprefix.prefixes=/r
      update_config:
        order: start-first
        failure_action: rollback
      resources:
        limits:
          memory: 128M
  backend-nginx:
    image: pldin601/myownradio-backend-nginx:latest
    networks:
      - default
      - global
    depends_on:
      - backend-php-fpm
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
      labels:
        - traefik.enable=true
        - traefik.http.routers.myownradio_backend.entryPoints=web,websecure
        - traefik.http.routers.myownradio_backend.rule=Host(`myownradio.biz`)
        - traefik.http.routers.myownradio_backend.tls=true
        - traefik.http.routers.myownradio_backend.tls.certresolver=resolver
        - traefik.http.services.myownradio_backend.loadbalancer.server.port=8080
      resources:
        limits:
          memory: 128M
  backend-php-fpm:
    image: pldin601/myownradio-backend-php:latest
    environment:
      DB_DATABASE: "mor"
      DB_HOST: "db"
      DB_PASSWORD: "mor"
      DB_USERNAME: "mor"
      FACEBOOK_APP_ID: "731742683610572"
      FACEBOOK_APP_SECRET: "f84af1cdddcc6ac06c6ebf606fb616c3"
      FFMPEG_PATH: "ffmpeg"
      MEDIAINFO_PATH: "mediainfo"
      JWT_KEY: "TbhX2QUfV7dfxOXILKlZWk6jF9OceHmvzzolIC0K"
      S3_ACCESS_KEY: "AKIAJBSFTKGMHDMPRPZA"
      S3_SECRET_KEY: "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"
      SENTRY_DSN: "https://2a74df546ce14acbb01fd71f1d00dfe7@sentry.io/2518976"
      BACKEND_STORAGE_LOCAL_DIR: /app/storage
      VIRTUAL_HOST: "myownradio.biz"
      LETSENCRYPT_HOST: "myownradio.biz"
      VIRTUAL_PORT: "8080"
      RADIO_STREAMER_ENDPOINT: "https://myownradio.biz/r"
      RADIO_STREAMER_TOKEN: "2a74df546ce14acbb01fd71f1d00dfe7"
    volumes:
      - /data/volumes/myownradio-storage:/app/storage
    depends_on:
      - db
      - streamer
      - storage
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
      resources:
        limits:
          memory: 256M
  storage:
    image: nginx:1.17
    environment:
      VIRTUAL_HOST: "fs1.myownradio.biz"
      LETSENCRYPT_HOST: "fs1.myownradio.biz"
      VIRTUAL_PORT: "80"
    volumes:
      - /data/volumes/myownradio-storage:/usr/share/nginx/html
    networks:
      - default
      - global
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
      labels:
        - traefik.enable=true
        - traefik.http.routers.myownradio_storage.entryPoints=web,websecure
        - traefik.http.routers.myownradio_storage.rule=Host(`fs1.myownradio.biz`)
        - traefik.http.routers.myownradio_storage.tls=true
        - traefik.http.routers.myownradio_storage.tls.certresolver=resolver
        - traefik.http.services.myownradio_storage.loadbalancer.server.port=80
      resources:
        limits:
          memory: 128M
  backend-dev:
    image: myownradio/backend-php-base:1.1.0
    command: 'php -d variables_order=EGPCS -S 0.0.0.0:8080 -t public server.php'
    environment:
      DB_DATABASE: "mor"
      DB_HOST: "db"
      DB_PASSWORD: "mor"
      DB_USERNAME: "mor"
      FACEBOOK_APP_ID: "731742683610572"
      FACEBOOK_APP_SECRET: "f84af1cdddcc6ac06c6ebf606fb616c3"
      FFMPEG_PATH: "ffmpeg"
      MEDIAINFO_PATH: "mediainfo"
      JWT_KEY: "TbhX2QUfV7dfxOXILKlZWk6jF9OceHmvzzolIC0K"
      S3_ACCESS_KEY: "AKIAJBSFTKGMHDMPRPZA"
      S3_SECRET_KEY: "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"
      SENTRY_DSN: "https://2a74df546ce14acbb01fd71f1d00dfe7@sentry.io/2518976"
      BACKEND_STORAGE_LOCAL_DIR: /app/storage
      RADIO_STREAMER_ENDPOINT: "https://myownradio.biz/r"
      RADIO_STREAMER_TOKEN: "2a74df546ce14acbb01fd71f1d00dfe7"
    networks:
      - default
      - global
    volumes:
      - /data/volumes/myownradio-storage:/app/storage
      - /data/dev/myownradio-backend-dev:/usr/app
    depends_on:
      - db
      - streamer
      - storage
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
      labels:
        - traefik.enable=true
        - traefik.http.routers.myownradio_backend_dev.entryPoints=web,websecure
        - traefik.http.routers.myownradio_backend_dev.rule=Host(`dev.myownradio.biz`)
        - traefik.http.routers.myownradio_backend_dev.tls=true
        - traefik.http.routers.myownradio_backend_dev.tls.certresolver=resolver
        - traefik.http.services.myownradio_backend_dev.loadbalancer.server.port=8080
      resources:
        limits:
          memory: 256M

volumes:
  mysql-data:
    name: mysql-data
    driver: local

networks:
  global:
    external: true
    name: global_default
