version: '3.5'
services:
  db:
    image: 'mysql:5.6'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      update_config:
        order: stop-first
        failure_action: rollback
  streamer:
    image: 'myownradio/stream-server:latest'
    environment:
      MOR_JDBC_LOGIN: "mor"
      MOR_JDBC_PASSWORD: "mor"
      MOR_JDBC_URL: "jdbc:mysql://db:3306/mor"
    networks:
      - default
      - global
    depends_on:
      - db
      - storage
    deploy:
      labels:
        - prometheus-job=yes
        - prometheus-port=8082
        - traefik.enable=true
        - traefik.http.routers.myownradio_streamer.entryPoints=web,websecure
        - traefik.http.routers.myownradio_streamer.rule=Host(`stream.myownradio.biz`)
        - traefik.http.routers.myownradio_streamer.tls=true
        - traefik.http.routers.myownradio_streamer.tls.certresolver=resolver
        - traefik.http.services.myownradio_streamer.loadbalancer.server.port=7778
      update_config:
        order: start-first
        failure_action: rollback
  backend:
    image: 'myownradio/backend:latest'
    environment:
      DB_DATABASE: "mor"
      DB_HOST: "db"
      DB_PASSWORD: "mor"
      DB_USERNAME: "mor"
      FACEBOOK_APP_ID: "731742683610572"
      FACEBOOK_APP_SECRET: "f84af1cdddcc6ac06c6ebf606fb616c3"
      FFMPEG_PATH: "ffmpeg"
      MEDIAINFO_PATH: "mediainfo"
      JWT_KEY: "TbhX2QUfV7dfxOXILKlZWk6jF9OceHmvzzolIC0K"
      S3_ACCESS_KEY: "AKIAJBSFTKGMHDMPRPZA"
      S3_SECRET_KEY: "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"
      STREAM_HOST: "https://stream.myownradio.biz"
      SENTRY_DSN: "https://2a74df546ce14acbb01fd71f1d00dfe7@sentry.io/2518976"
      BACKEND_STORAGE_LOCAL_DIR: /app/storage
    networks:
      - default
      - global
    volumes:
      - /data/volumes/myownradio-storage:/app/storage
    depends_on:
      - db
      - streamer
      - storage
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
      labels:
        - traefik.enable=true
        - traefik.http.routers.myownradio_backend.entryPoints=web,websecure
        - traefik.http.routers.myownradio_backend.rule=Host(`myownradio.biz`)
        - traefik.http.routers.myownradio_backend.tls=true
        - traefik.http.routers.myownradio_backend.tls.certresolver=resolver
        - traefik.http.services.myownradio_backend.loadbalancer.server.port=8080
  storage:
    image: nginx:1.17
    volumes:
      - /data/volumes/myownradio-storage:/usr/share/nginx/html
    networks:
      - default
      - global
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
      labels:
        - traefik.enable=true
        - traefik.http.routers.myownradio_storage.entryPoints=web,websecure
        - traefik.http.routers.myownradio_storage.rule=Host(`fs1.myownradio.biz`)
        - traefik.http.routers.myownradio_storage.tls=true
        - traefik.http.routers.myownradio_storage.tls.certresolver=resolver
        - traefik.http.services.myownradio_storage.loadbalancer.server.port=80
volumes:
  mysql-data:
    name: mysql-data
    driver: local

networks:
  global:
    external: true
    name: global_default
