version: "3.5"

services:
  db:
    image: "mysql:5.6"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mor"
      MYSQL_USER: "mor"
      MYSQL_PASSWORD: "mor"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 13306:3306
    deploy:
      update_config:
        order: stop-first

  streamer:
    image: "myownradio/stream-server:latest"
    environment:
      MOR_JDBC_LOGIN: "mor"
      MOR_JDBC_PASSWORD: "mor"
      MOR_JDBC_URL: "jdbc:mysql://db:3306/mor"
      VIRTUAL_HOST: "stream.myownradio.biz"
      VIRTUAL_PORT: "7778"
      VIRTUAL_NETWORK: 1
    depends_on:
      - db
    deploy:
      update_config:
        order: start-first

  web:
    image: "myownradio/myownradio-universe:latest"
    env_file:
      - web.env
    environment:
      DB_DATABASE: "mor"
      DB_HOST: "db"
      DB_PASSWORD: "mor"
      DB_USERNAME: "mor"
      FFMPEG_PATH: "ffmpeg"
      MEDIAINFO_PATH: "mediainfo"
      STREAM_HOST: "https://stream.myownradio.biz"
      VIRTUAL_HOST: "myownradio.biz"
      VIRTUAL_PORT: "80"
      VIRTUAL_NETWORK: 1
    depends_on:
      - db
      - streamer
    deploy:
      update_config:
        order: start-first

  proxy:
    image: pldin601/nginx-proxy-upload
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  mysql-data:
    name: mysql-data
    driver: local
