name: trigger radiomanager-web-egress-controller image build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'services/radiomanager-web-egress-controller/**'
      - '.github/workflows/build-radiomanager-web-egress-controller.yml'

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: trigger the build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-image
          client-payload: |
            {
              "image_name": "pldin601/myownradio-radiomanager-web-egress-controller",
              "dockerfile": "services/radiomanager-web-egress-controller/Dockerfile",
              "context": "services/radiomanager-web-egress-controller",
              "token": "${{ secrets.REPO_ACCESS_TOKEN }}"
            }
