name: build an image

on:
  repository_dispatch:
    types:
      - build-image

jobs:
  get_build:
    name: get current build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%y.%m')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    outputs:
      build_id: ${{ steps.vars.outputs.date }}.${{ github.run_id }}-${{ steps.vars.outputs.sha_short }}

  main:
    needs: [get_build]
    name: build ${{ github.event.client_payload.image_name }}:${{ needs.get_build.outputs.build_id }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.event.client_payload.image_name }}
      DOCKERFILE: ${{ github.event.client_payload.dockerfile }}
      CONTEXT: ${{ github.event.client_payload.context }}
      BUILD_ID: ${{ needs.get_build.outputs.build_id }}
    steps:
      - name: Build
        uses: pldin601/build-multiarch-on-aws-spots/.github/workflows/build-multiarch-on-aws-spots.yml@master
        with:
          DOCKER_IMAGE_TAG: ${{ env.BUILD_ID }}
          WORKFLOW_CHECKOUT: master # Should be the same as the ref used in "uses" expression.
          AWS_REGION: eu-central-1
          AWS_EC2_INSTANCE_SIZE: large
        secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
      - name: checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: builder
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          file: ${{ env.DOCKERFILE }}
          context: ${{ env.CONTEXT }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }}
            ${{ env.IMAGE_NAME }}:latest
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Leave comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            New docker image has been successfully built:

                ${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }}
                ${{ env.IMAGE_NAME }}:latest
