name: trigger radio-streamer image build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
      - 'images/migration/**'
      - '.github/workflows/build-migration.yml'

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: trigger the build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-image
          client-payload: |
            {
              "image_name": "pldin601/myownradio-mysql-migration",
              "dockerfile": "images/migration/Dockerfile",
              "context": ".",
              "token": "${{ secrets.REPO_ACCESS_TOKEN }}"
            }
