name: build an image

on:
  repository_dispatch:
    types:
      - build-image

jobs:
  get_build:
    name: get current build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%y.%m')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    outputs:
      build_id: ${{ steps.vars.outputs.date }}.${{ github.run_id }}-${{ steps.vars.outputs.sha_short }}

  build:
    needs: [get_build]
    name: Build and push
    uses: pldin601/build-multiarch-on-aws-spots/.github/workflows/build-multiarch-on-aws-spots.yml@b1d3244aa22fefb2e6bca29fc5202a5016f2f88c
    with:
      DOCKER_IMAGE_TAG: ${{ needs.get_build.outputs.build_id }}
      WORKFLOW_CHECKOUT: b1d3244aa22fefb2e6bca29fc5202a5016f2f88c # Should be the same as the ref used in "uses" expression.
      AWS_REGION: eu-west-2
      AWS_EC2_INSTANCE_SIZE: large
      BUILD_CONTEXT: ${{ github.event.client_payload.context }}
      BUILD_DOCKERFILE: ${{ github.event.client_payload.dockerfile }}
      REPOSITORY_URL: https://${{ github.event.client_payload.token }}@github.com/${{ github.repository }}.git
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
