name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build-backend-nginx:
    name: Build backend-nginx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup
        uses: docker/setup-buildx-action@v1
        id: builder
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          file: images/backend-nginx/Dockerfile
          context: services/backend
          push: true
          tags: |
            pldin601/myownradio-backend-nginx:latest
            pldin601/myownradio-backend-nginx:${{ github.sha }}

  build-backend-php:
    name: Build backend-php
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup
        uses: docker/setup-buildx-action@v1
        id: builder
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          file: images/backend-php/Dockerfile
          context: services/backend
          push: true
          tags: |
            pldin601/myownradio-backend-nginx:latest
            pldin601/myownradio-backend-nginx:${{ github.sha }}

  build-radio-streamer:
    name: Build radio-streamer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: myownradio/radio-streamer
          tags: latest
          path: services/radio-streamer

  deploy:
    needs:
      - build-backend-nginx
      - build-backend-php
      - build-radio-streamer
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Push stack to production
        uses: pldin601/docker-swarm-deploy-action@master
        with:
          remote_host: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_IP_ADDRESS }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          args: stack deploy --with-registry-auth --prune --resolve-image=always --compose-file myownradio-platform/docker-compose.production.yml myownradio
