name: Deploy to Production

on:
  push:
    branches:
      - master
    paths:
      - 'images/**'
      - 'services/**'
      - 'migrations/**'

jobs:
  build-backend-nginx:
    name: Build backend-nginx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%y.%m')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup
        uses: docker/setup-buildx-action@v1
        id: builder
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          file: images/backend-nginx/Dockerfile
          context: services/backend
          push: true
          tags: |
            pldin601/myownradio-backend-nginx:${{ steps.vars.outputs.date }}.${{ github.run_id }}-${{ steps.vars.outputs.sha_short }}
            pldin601/myownradio-backend-nginx:latest

  build-backend-php:
    name: Build backend-php
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%y.%m')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup
        uses: docker/setup-buildx-action@v1
        id: builder
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          file: images/backend-php/Dockerfile
          context: services/backend
          push: true
          tags: |
            pldin601/myownradio-backend-php:${{ steps.vars.outputs.date }}.${{ github.run_id }}-${{ steps.vars.outputs.sha_short }}
            pldin601/myownradio-backend-php:latest

  build-radio-streamer:
    name: Build radio-streamer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%y.%m')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup
        uses: docker/setup-buildx-action@v1
        id: builder
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          file: services/radio-streamer/Dockerfile
          context: services/radio-streamer
          push: true
          tags: |
            pldin601/myownradio-radio-streamer:${{ steps.vars.outputs.date }}.${{ github.run_id }}-${{ steps.vars.outputs.sha_short }}
            pldin601/myownradio-radio-streamer:latest
