name: Build Images

on:
  push:
    branches:
      - master
    paths:
      - '!services/radio-streamer/**'
      - '!services/backend/**'
      - 'images/**'
      - 'services/**'
      - 'migrations/**'

jobs:
  release_version:
    name: Compose release version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Variables
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%y.%m')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    outputs:
      version: ${{ steps.vars.outputs.date }}.${{ github.run_id }}-${{ steps.vars.outputs.sha_short }}
