name: 'Mirror to GitLab'

on:
  push:
    branches:
      - master

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        uses: wei/git-sync@v1
        env:
          SOURCE_REPO: ${{ github.repository }}
          SOURCE_BRANCH: master
          DESTINATION_REPO: git@gitlab.com:radioteria/myownradio-platform.git
          DESTINATION_BRANCH: master
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
