name: Test radiomanager-frontend build

on:
  push:
    branches:
      - '**'
    paths:
      - 'services/radiomanager-frontend/**'

jobs:
  main:
    name: Test radiomanager-frontend build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: |
          npm ci
          npm run build --if-present
        working-directory: 'services/radiomanager-frontend'
