name: Test radiomanager-frontend build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'services/radiomanager-frontend/**'

jobs:
  main:
    name: Setup Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present
